version: '3.8'

services:
  cryptoconfigdb:
    image: postgres:latest
    
  pgadmin:
    image: dpage/pgadmin4:latest
  
  rabbitmq:
    image: rabbitmq:3-management
  
  seq:
    image: datalust/seq:latest
  
  cryptoagent.coinapi:
    image: ${DOCKER_REGISTRY-}cryptoagent
    build:
      context: .
      dockerfile: Services/CryptoAgent/CryptoAgent.CoinAPI/Dockerfile

  configagent.api:
    image: ${DOCKER_REGISTRY-}configagent
    build:
      context: .
      dockerfile: Services/ConfigAgent/ConfigAgent.API/Dockerfile
      
volumes: 
  configdb_data:
  pgadmin_data: